version: '3'

services:
  kong-gateway:
    image: kong/kong-gateway:3.2.2.1
    hostname: kong-apigw
    container_name: kong-api-gateway
    # network_mode: host
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yaml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_ADMIN_GUI_URL: "http://localhost:5002"
    command: "kong start"
    ports:
      - 5000:8000
      - 5001:8001
      - 5002:8002
      - 5003:8003
      - 5004:8004
      - 5443:8443
      - 5444:8444
      - 5445:8445
    volumes:
      - ./:/kong/declarative/
